# Generated by Django 3.2.12 on 2022-06-13 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='username')),
                ('password', models.CharField(max_length=64, verbose_name='password')),
            ],
        ),
    ]
